#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
echo "dotfiles = " $DOTFILES
echo "stow_folders = " $STOW_FOLDERS

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    echo $folder
    stow $folder
done
popd
