#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    #STOW_FOLDERS="test"
    STOW_FOLDERS="stow,bash,zsh,vim,bin"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

echo "# ========================================================== #"
echo "# STOW_FOLDERS = "$STOW_FOLDERS
echo "# DOTFILES = "$DOTFILES
echo "# ========================================================== #"

#$DOTFILES/install
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "==>> Removing $folder"
    stow -D $folder
    echo "<<== Adding $folder"
    stow $folder
done
popd

